import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Banner from "../components/Banner";
import Header from "../components/Header";
import ProductsByCategories from "../components/productByCategories";
import Selling from "../components/Selling";
import { fetchCategories } from "../utils/getCategories";

interface Props {
  categories: Category[];
}

const Home = ({ categories }: Props) => {
  return (
    <>
      <Head>
        <title>PureBeauty</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      {/* products By Categories COMPONENT*/}
      <ProductsByCategories categories={categories} />

      {/* Banner Company */}
      <Banner />
      <Selling />
      {/* products By Brands */}
      {/* <ProductsByBrand /> */}
    </>
  );
};

export default Home;

// SERVER Side props NEXT.js
export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const categories = await fetchCategories();

  return {
    props: {
      categories,
    },
  };
};
