import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Banner from "../components/Banner";
import Header from "../components/Header";
import ProductsByBrand from "../components/ProductsByBrand";
import ProductsByType from "../components/productByType";
import fetchBrands from "../utils/fetchBrands";

const Home: NextPage = ({ brandsData }: any) => {
  const [brandsName, setBrandsName] = useState(brandsData);
  return (
    <>
      <Head>
        <title>PureBeauty</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      {/* products By type */}
      <ProductsByType />

      {/* Banner */}
      <Banner />
      {/* products By Brands */}
      <ProductsByBrand />
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const response = await fetchBrands();

  return {
    props: {
      brandsData: response,
    },
  };
};
